### ISSUE TITLE
Feature Request: Volume Control

### ISSUE THREAD

**Issue by Norc** [JacobMcAuley/combatready#1]
The volume is... loud. Some volume control is badly necessary. Ideally a per-user setting would be best, but a master volume slider for GMs would be a huge improvement.

**Comment by JacobMcAuley** [comment]
Hi Norc,
Because I love to spam your feed I'm closing this notification a month late :D.
Just going to link the developer who is maintaining this module now, although I know you already know https://github.com/smilligan93/combatready.
