### ISSUE TITLE
Feature Request: Easier clicking to start turn

### ISSUE THREAD

**Issue by Norc** [JacobMcAuley/combatready#2]
In my experience (and I've also seen this on Foundry Discord) it can be difficult to actually start your turn, sometimes I click as a player and it feels like nothing happens.

**Comment by JacobMcAuley** [comment]
Hi Norc,
Because I love to spam your feed I'm closing this notification a month late :D.
Just going to link the developer who is maintaining this module now, although I know you already know https://github.com/smilligan93/combatready.
