### ISSUE TITLE
Next Up animation issues

### ISSUE THREAD

**Issue by Nnayl** [JacobMcAuley/combatready#3]
Hi,

The last element in the list of turn orders sends the animation "Next Up" to the first element, while the following turn restarts all initiatives.

Sample :
When last NPC start, Character receive "Next Up" Animation. But next turn, is not Character in first position.

![image](https://user-images.githubusercontent.com/11646183/84571722-6c7bb380-ad95-11ea-999c-f7a201b9064b.png)

Thanks, for job !

**Comment by JacobMcAuley** [comment]
Hi Nnayl,

This module is no longer being developed as it's activate maintenance has been taken over by another user located here https://github.com/smilligan93/combatready.

Thanks for the issue report though!
