### ISSUE TITLE
Compatibility issue with Savage World System

### ISSUE THREAD

**Issue by Nnayl** [JacobMcAuley/combatready#4]
The "Your Turn" animation designate the wrong actor during a new turn in the combat tracker. During each new turn the"Your Turn" animation designate the first PC character created, not the first Actor on combat tracker

**Environment Details**
Foundry VTT Version: 0.6.2
Savage World Adventure : 0.9.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11646183/84572403-f0379f00-ad99-11ea-9753-d9136216b209.png)

**Additional context**
it s happen with Savage World Adventure System. The initiative don't use numeric system but a deck of playing card.

**Comment by JacobMcAuley** [comment]
Hi Nnayl,

This module is no longer being developed as it's activate maintenance has been taken over by another user located here https://github.com/smilligan93/combatready.

Thanks for the issue report though!
